import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width" />
      </head>
      <body className="dark">
        <header><nav><li>home</li></nav></header>
        {children}
        <footer><nav><li>test</li></nav></footer>
      </body>
    </html>
  )
}
